### ISSUE TITLE
sh script/bootstrap fails with errors

### ISSUE THREAD

**Issue by andyrat33** [crits/crits#464] opened 2015-04-26 21:06 UTC
-- snip --
Cleaning up...
Dependency installations complete!
Setting up crits.log file
Creating default database configuration file
sed: can't read : No such file or directory
Creating default collections
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 399, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 392, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 272, in fetch_command
    klass = load_command_class(app_name, subcommand)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 75, in load_command_class
    module = import_module('%s.management.commands.%s' % (app_name, name))
  File "/usr/local/lib/python2.7/dist-packages/django/utils/importlib.py", line 40, in import_module
    __import__(name)
  File "/home/andy/crits/crits/core/management/commands/create_default_collections.py", line 8, in <module>
    from create_event_types import add_event_types
  File "/home/andy/crits/crits/core/management/commands/create_event_types.py", line 3, in <module>
    from crits.events.event import EventType
  File "/home/andy/crits/crits/events/event.py", line 7, in <module>
    from crits.core.crits_mongoengine import CritsSchemaDocument, CritsBaseAttributes
  File "/home/andy/crits/crits/core/crits_mongoengine.py", line 23, in <module>
    from mongoengine import QuerySetNoCache as QS
ImportError: cannot import name QuerySetNoCache

**Comment by mgoffin** [comment] 2015-04-26 21:11
What mongoengine version did you install? This error is usually because of a (I think) newer version of MongoEngine.

**Comment by andyrat33** [comment] 2015-04-26 21:49
Thanks for the reply but I did not install any - this was the first instruction for the install:
sh script/bootstrap

If there was something that I should have done before this, then it may be missing from the instructions.

**Comment by andyrat33** [comment] 2015-04-26 21:50
Sorry, should have said OS is Ubuntu 14 LTS

**Comment by mgoffin** [comment] 2015-04-26 22:22
I wasn't very clear. It installs mongo engine and I'm looking for what version was installed. It's possible we need to tighten up or requirements.txt for mongo engine and put a max version on it.

**Comment by jezkerwin** [comment] 2015-04-27 13:38
I just performed an install using the bootstrap file on a CentOS 7 Base install and received the same error. I then took the mongoengine line from requirements.txt and did a pip install manually, that seem to install version 0.8.7 of mongoengine. I then re-ran the bootstrap script and this error was displayed.

```
Downloading/unpacking mongoengine>=0.8.1,<0.8.2 (from django-tastypie-mongoengine==0.4.5->-r requirements.txt (line 12))
  Downloading mongoengine-0.8.1.tar.gz (181kB): 181kB downloaded
  Running setup.py (path:/tmp/pip-build-aywv88/mongoengine/setup.py) egg_info for package mongoengine
    0.8.1
   
    no previously-included directories found matching 'docs/_build'
Installing collected packages: mongoengine
  Found existing installation: mongoengine 0.8.7
    Uninstalling mongoengine:
      Successfully uninstalled mongoengine
  Running setup.py install for mongoengine
    0.8.1
```

**Comment by dsnellgrove** [comment] 2015-04-27 17:05
There's a conflict in the versions of the libraries. The version of django-tastypie-mongoengine requires no later version of mongoengine than 0.8.1 but CRITs uses 0.8.7. You have to set both versions on the same pip install to force them both in together otherwise django-tastypie-mongoengine forces a downgrade.

**Comment by andyrat33** [comment] 2015-04-27 21:51
I tried again and this may help:

Downloading/unpacking olefile (from -r requirements.txt (line 34))
  Downloading olefile-0.42.1.zip (119kB): 119kB downloaded
  Running setup.py (path:/tmp/pip_build_root/olefile/setup.py) egg_info for package olefile
    
Requirement already satisfied (use --upgrade to upgrade): mongoengine>=0.8.1,<0.8.2 in /usr/local/lib/python2.7/dist-packages (from django-tastypie-mongoengine==0.4.5->-r requirements.txt (line 12))
Installing collected packages: olefile
  Running setup.py install for olefile
    
Successfully installed olefile
Cleaning up...
Dependency installations complete!
Setting up crits.log file
Creating default database configuration file
sed: can't read : No such file or directory
Creating default collections
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 399, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 392, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 272, in fetch_command
    klass = load_command_class(app_name, subcommand)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 75, in load_command_class
    module = import_module('%s.management.commands.%s' % (app_name, name))
  File "/usr/local/lib/python2.7/dist-packages/django/utils/importlib.py", line 40, in import_module
    __import__(name)
  File "/home/andy/crits/crits/core/management/commands/create_default_collections.py", line 8, in <module>
    from create_event_types import add_event_types
  File "/home/andy/crits/crits/core/management/commands/create_event_types.py", line 3, in <module>
    from crits.events.event import EventType
  File "/home/andy/crits/crits/events/event.py", line 7, in <module>
    from crits.core.crits_mongoengine import CritsSchemaDocument, CritsBaseAttributes
  File "/home/andy/crits/crits/core/crits_mongoengine.py", line 23, in <module>
    from mongoengine import QuerySetNoCache as QS
ImportError: cannot import name QuerySetNoCache

**Comment by jezkerwin** [comment] 2015-04-28 00:45
dsnellgrove, how would I set both versions on the same pip install?

**Comment by dsnellgrove** [comment] 2015-04-28 11:14
What is the output of $ pip freeze  ?

**Comment by dsnellgrove** [comment] 2015-04-28 11:22
I'm able to get the same error by following this procedure:
Clone crits repository
git submodule init
git submodule update
vagrant up
vagrant ssh
run /vagrant/scripts/bootstrap

Ending output is a downgrade of mongoengine to the wrong version and the error from this bug:
https://gist.github.com/dsnellgrove/fcd5111b37d0f980677e

**Comment by dsnellgrove** [comment] 2015-04-28 11:31
Confirmed that that error is specifically because of having the wrong (0.8.1) version of mongoengine installed, which the bootstrap script causes to be installed every time it is run. Had to manually install the correct (0.8.7) version then removed the requirements.txt file so bootstrap would stop downgrading it, allowing the initialization of the collections to occur.

**Comment by dsnellgrove** [comment] 2015-04-29 15:35
If https://github.com/crits/crits/blob/master/requirements.txt#L16 with mongoengine on it wasn't working it should be removed. I've never seen that syntax used in a requirements.txt file so I don't know that it's even valid. I suspect it wasn't and mongoengine was just being pulled in as a dependency before #473

**Comment by frbapolkosnik** [comment] 2015-05-01 18:07
Please see #479 , I think that pip is very picky when it comes to parsing the requirements file and if the line:
`--allow-external mongoengine mongoengine==0.8.7`
is not split into:
`--allow-external mongoengine
mongoengine==0.8.7`
then the mongoengine version requirements are simply ignored.

**Comment by decompile** [comment] 2015-05-03 14:14
used the new requests.txt but got the same error.

**Comment by decompile** [comment] 2015-05-03 14:27
manually installed 0.8.7 
error changed to __init__() got an unexpected keyword argument 'snapshot'

**Comment by apolkosnik** [comment] 2015-05-03 14:29
Could you please explain how you tested? Did you remove all the mongoengine
packages or did you use something like fresh install /livecd?

Thanks,
Adam

**Comment by decompile** [comment] 2015-05-03 14:32
Hi i removed the mongoengine and used pip to install the correct version

**Comment by decompile** [comment] 2015-05-03 14:34
OK got it to work.
the problem was both the mongoengine and PyMongo version.

my fix:
pip uninstall mongoengine
pip uninstall pymongo
pip install mongoengine==0.8.7
pip install pymongo==2.7.2

**Comment by frbapolkosnik** [comment] 2015-05-04 14:50
This should be now fixed via  #479

**Comment by frbapolkosnik** [comment] 2015-05-04 18:57
BTW. There might be instances where SECRET_KEY generated contains an ampersand, in such case the "&" will be replaced with "SECRET_KEY" value. Pull Request #477 should be able to alleviate such issue from reoccurring.

**Comment by mgoffin** [comment] 2015-09-15 17:12
Recent PRs have solved these problems.

**Closed by mgoffin** 2015-09-15 17:12 UTC
