### ISSUE TITLE
Issue with AD Integration for CRITS

### ISSUE THREAD

**Issue by jcalafiore** [crits/crits#381] opened 2015-01-30 17:45 UTC
Hi,
 I am wondering if anyone has had any issues or success with using the AD Integration for CRITS. I have not had any success with it and was wondering anyone also had any difficulty getting it work. I was under the impression that it does not require bind to be established to work.

I've tried doing some troubleshooting with ldapsearch for example:
ldapsearch -h 10.0.0.1 -p 389 -x -D "uid=jason,ou=Users Accounts,dc=sub,dc=example,dc=com" -W  -d 255

It returns: 
ldap_msgfree
ldap_err2string
ldap_bind: Invalid credentials (49)
        additional info: 80090308: LdapErr: DSID-0C0903A9, comment: AcceptSecurityContext error, data 52e, v1db1
ldap_free_connection 1 1
ldap_send_unbind
ber_flush2: 7 bytes to sd 3
  0000:  30 05 02 01 02 42 00                               0....B.
ldap_write: want=7, written=7
  0000:  30 05 02 01 02 42 00                               0....B.
ldap_free_connection: actually freed

Thank you
Jason

**Comment by frbapolkosnik** [comment] 2015-01-30 20:14
I've not done it with AD directly, but I think that the thing that might be problematic in your case is the default user_cn (which is 'cn=') that gets slapped on to the bind_s call. For AD you probably need it to be 'uid=', you can try to specify it in the LDAP settings as 'uid='. If that doesn't work, you can try merging the pull 313 (LDAP bind_dn support #313) and it could fix the situation for you, also it adds support for bind_dn, so that you can use bind_dn + bind_dn password to perform user_dn lookups (especially when anonymous binds are disabled by the AD admins or when you have multiple LDAP servers and using the userid for user_dn just doesn't cut it).

If you want to experiment a bit:
Open up a shell, start up a python shell, and paste in this (after populating it with your specific values) in the python shell on your CRITs machine:

#This is pretty much what transpires with LDAP turned on)
import ldap, ldapurl
# using ldaps here, hence port 636
ldap_server = '<yourLDAPServer>',636
scheme = "ldaps"
url = ldapurl.LDAPUrl('%s://%s' % (scheme, ldap_server[0]))
l = ldap.initialize('%s:%s' % (url.unparse(), ldap_server[1]))
l.protocol_version = 3
l.set_option(ldap.OPT_REFERRALS, 0)
l.set_option(ldap.OPT_TIMEOUT, 10)
#you might want to fill that in or leave blank
base_dn = 'dc=example,dc=com'
un = '<username for auth>'
password = '<yeah... your password>'
l.simple_bind_s( un, password)
result = l.search_s(base_dn,ldap.SCOPE_SUBTREE,'cn=<SomeuserName>')
print result

In some cases cn=<SomeuserName> can be replaced with uid=<SomeuserName>...

Best regards,
Adam

**Comment by jcalafiore** [comment] 2015-02-02 18:55
Hi Adam,
 I tried your python script and populated values in.

import ldap, ldapurl
#using ldaps here, hence port 636
ldap_server = "ldap://example.com",636
scheme = "ldaps"
url = ldapurl.LDAPUrl('%s://%s' % (scheme, ldap_server[0]))
l = ldap.initialize('%s:%s' % (url.unparse(), ldap_server[1]))
l.protocol_version = 3
l.set_option(ldap.OPT_REFERRALS, 0)
l.set_option(ldap.OPT_TIMEOUT, 10)
#you might want to fill that in or leave blank
base_dn = "dc=example,dc=com"
un = "jason"
password = "password"
l.simple_bind_s( un, password)
result = l.search_s(base_dn,ldap.SCOPE_SUBTREE,'cn=')
print result

I then received this error...

Traceback (most recent call last):
  File "ldapsearch.py", line 7, in <module>
    l = ldap.initialize('%s:%s' % (url.unparse(), ldap_server[1]))
  File "/usr/local/lib/python2.7/dist-packages/python_ldap-2.4.15-py2.7-linux-x86_64.egg/ldap/functions.py", line 91, in initialize
    return LDAPObject(uri,trace_level,trace_file,trace_stack_limit)
  File "/usr/local/lib/python2.7/dist-packages/python_ldap-2.4.15-py2.7-linux-x86_64.egg/ldap/ldapobject.py", line 70, in __init__
    self._l = ldap.functions._ldap_function_call(ldap._ldap_module_lock,_ldap.initialize,uri)
  File "/usr/local/lib/python2.7/dist-packages/python_ldap-2.4.15-py2.7-linux-x86_64.egg/ldap/functions.py", line 63, in _ldap_function_call
    result = func(*args,**kwargs)
ldap.LDAPError: (2, 'No such file or directory')

**Comment by apolkosnik** [comment] 2015-02-02 19:32
Instead of:
result = l.search_s(base_dn,ldap.SCOPE_SUBTREE,'cn=')
print result

try
result = l.search_s(base_dn,ldap.SCOPE_SUBTREE,'uid=jason')
print result

jason or some other username...

**Comment by jcalafiore** [comment] 2015-02-03 19:50
Hi Adam,
 I gave it another try and received this error.

Traceback (most recent call last):
  File "ldapsearch.py", line 7, in <module>
    l = ldap.initialize('%s:%s' % (url.unparse(), ldap_server[1]))
  File "/usr/local/lib/python2.7/dist-packages/python_ldap-2.4.15-py2.7-linux-x86_64.egg/ldap/functions.py", line 91, in initialize
    return LDAPObject(uri,trace_level,trace_file,trace_stack_limit)
  File "/usr/local/lib/python2.7/dist-packages/python_ldap-2.4.15-py2.7-linux-x86_64.egg/ldap/ldapobject.py", line 70, in __init__
    self._l = ldap.functions._ldap_function_call(ldap._ldap_module_lock,_ldap.initialize,uri)
  File "/usr/local/lib/python2.7/dist-packages/python_ldap-2.4.15-py2.7-linux-x86_64.egg/ldap/functions.py", line 63, in _ldap_function_call
    result = func(*args,**kwargs)
ldap.LDAPError: (2, 'No such file or directory')

**Comment by apolkosnik** [comment] 2015-02-03 19:52
yeah,  you must be missing the ldap tools on your linux system

**Comment by jcalafiore** [comment] 2015-02-03 19:58
Hi Adam,
 I have this version installed. Is this not the correct one?

Package: ldap-utils
Status: install ok installed
Priority: optional
Section: net
Installed-Size: 682
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Architecture: amd64
Source: openldap
Version: 2.4.28-1.1ubuntu4.4

**Comment by apolkosnik** [comment] 2015-02-03 20:02
Actually, remove ldap:// from your ldap_server location.

**Comment by jcalafiore** [comment] 2015-02-03 20:09
Traceback (most recent call last):
  File "ldapsearch.py", line 15, in <module>
    l.simple_bind_s(un, password)
  File "/usr/local/lib/python2.7/dist-packages/python_ldap-2.4.15-py2.7-linux-x86_64.egg/ldap/ldapobject.py", line 207, in simple_bind_s
    msgid = self.simple_bind(who,cred,serverctrls,clientctrls)
  File "/usr/local/lib/python2.7/dist-packages/python_ldap-2.4.15-py2.7-linux-x86_64.egg/ldap/ldapobject.py", line 201, in simple_bind
    return self._ldap_call(self._l.simple_bind,who,cred,RequestControlTuples(serverctrls),RequestControlTuples(clientctrls))
  File "/usr/local/lib/python2.7/dist-packages/python_ldap-2.4.15-py2.7-linux-x86_64.egg/ldap/ldapobject.py", line 99, in _ldap_call
    result = func(*args,**kwargs)
ldap.SERVER_DOWN: {'info': 'Error in the push function.', 'desc': "Can't contact LDAP server"}

**Comment by frbapolkosnik** [comment] 2015-02-03 20:20
It looks better now, is your ldap server listening on 389 and is using ldap (not the secure ldap or ldaps)?

Change :
scheme = 'ldap'
Ldap_server = '10.0.0.1', 389

**Comment by jcalafiore** [comment] 2015-02-03 20:38
Hi Adam, 

I received the following after the changes suggested...

Traceback (most recent call last):
  File "ldapsearch.py", line 15, in <module>
    l.simple_bind_s(un, password)
  File "/usr/local/lib/python2.7/dist-packages/python_ldap-2.4.15-py2.7-linux-x86_64.egg/ldap/ldapobject.py", line 208, in simple_bind_s
    resp_type, resp_data, resp_msgid, resp_ctrls = self.result3(msgid,all=1,timeout=self.timeout)
  File "/usr/local/lib/python2.7/dist-packages/python_ldap-2.4.15-py2.7-linux-x86_64.egg/ldap/ldapobject.py", line 469, in result3
    resp_ctrl_classes=resp_ctrl_classes
  File "/usr/local/lib/python2.7/dist-packages/python_ldap-2.4.15-py2.7-linux-x86_64.egg/ldap/ldapobject.py", line 476, in result4
    ldap_result = self._ldap_call(self._l.result4,msgid,all,timeout,add_ctrls,add_intermediates,add_extop)
  File "/usr/local/lib/python2.7/dist-packages/python_ldap-2.4.15-py2.7-linux-x86_64.egg/ldap/ldapobject.py", line 99, in _ldap_call
    result = func(*args,**kwargs)
ldap.INVALID_CREDENTIALS: {'info': '80090308: LdapErr: DSID-0C0903A9, comment: AcceptSecurityContext error, data 52e, v1db1', 'desc': 'Invalid credentials'}

**Comment by apolkosnik** [comment] 2015-02-03 20:40
At least that is consistent with your first post... Now you need to figure
out what's wrong with the credentials you are using to connect.

**Comment by jcalafiore** [comment] 2015-02-03 21:43
I was able to get the following message below using 2 other accounts. The main difference between the different accounts seem to be the Groups they are associated with, though all are Domain Accounts.

[(None, ['ldap://ForestDnsZones.example.com/DC=ForestDnsZones,DC=example,DC=com']), (None, ['ldap://DomainDnsZones.example.com/DC=DomainDnsZones,DC=example,DC=com']), (None, ['ldap://example.com/CN=Configuration,DC=example,DC=com'])]

I tried to login on the CRITS web console using one of the accounts that worked with the script and received Bad Username or password.

**Comment by apolkosnik** [comment] 2015-02-03 23:28
Can you test two versions of the script one with this

result = l.search_s(base_dn,ldap.SCOPE_SUBTREE,'cn=jason')
print result

and the other

result = l.search_s(base_dn,ldap.SCOPE_SUBTREE,'uid=jason')
print result

and then let me know which one works for you?

if the one that has uid=username, then you can either modify the user.py or
try the patch that I mentioned in the second post.

**Comment by jcalafiore** [comment] 2015-02-04 14:26
Hi Adam,
 It appears to be giving the same error for both incidents with the 'Jason' account...

Traceback (most recent call last):
  File "ldapsearch2.py", line 15, in <module>
    l.simple_bind_s(un, password)
  File "/usr/local/lib/python2.7/dist-packages/python_ldap-2.4.15-py2.7-linux-x86_64.egg/ldap/ldapobject.py", line 208, in simple_bind_s
    resp_type, resp_data, resp_msgid, resp_ctrls = self.result3(msgid,all=1,timeout=self.timeout)
  File "/usr/local/lib/python2.7/dist-packages/python_ldap-2.4.15-py2.7-linux-x86_64.egg/ldap/ldapobject.py", line 469, in result3
    resp_ctrl_classes=resp_ctrl_classes
  File "/usr/local/lib/python2.7/dist-packages/python_ldap-2.4.15-py2.7-linux-x86_64.egg/ldap/ldapobject.py", line 476, in result4
    ldap_result = self._ldap_call(self._l.result4,msgid,all,timeout,add_ctrls,add_intermediates,add_extop)
  File "/usr/local/lib/python2.7/dist-packages/python_ldap-2.4.15-py2.7-linux-x86_64.egg/ldap/ldapobject.py", line 99, in _ldap_call
    result = func(*args,**kwargs)
ldap.INVALID_CREDENTIALS: {'info': '80090308: LdapErr: DSID-0C0903A9, comment: AcceptSecurityContext error, data 52e, v1db1', 'desc': 'Invalid credentials'}

For my test account I am getting this with 'cn=testuser1'

[('CN=testuser1,OU=Example User Accounts,DC=example,DC=com', {'primaryGroupID': ['513'], 'logonCount': ['6'], 'cn': ['testuser1'], 'countryCode': ['0'], 'dSCorePropagationData': ['16010101000000.0Z'], 'objectClass': ['top', 'person', 'organizationalPerson', 'user'], 'userPrincipalName': ['testuser1@example.com'], 'lastLogonTimestamp': ['130674708623981184'], 'instanceType': ['4'], 'distinguishedName': ['CN=testuser1,OU=Example User Accounts,DC=example,DC=com'], 'sAMAccountType': ['805306368'], 'objectSid': ['\x01\x05\x00\x00\x00\x00\x00\x05\x15\x00\x00\x00\xd0Y@\xear\x06\xfd\x95\xfe\xe6v\x10t\x06\x00\x00'], 'whenCreated': ['20141008131856.0Z'], 'uSNCreated': ['22856477'], 'badPasswordTime': ['130574436836521218'], 'pwdLastSet': ['130674735099436254'], 'sAMAccountName': ['testuser1'], 'objectCategory': ['CN=Person,CN=Schema,CN=Configuration,DC=example,DC=com'], 'objectGUID': ['\x1d\x1d"0\x0c\x17\x88E\xbb\xae}Tn\x08&\xbf'], 'whenChanged': ['20150203214534.0Z'], 'badPwdCount': ['0'], 'accountExpires': ['9223372036854775807'], 'displayName': ['testuser1'], 'name': ['testuser1'], 'memberOf': ['CN=CIRTUsers,OU=Groups,DC=example,DC=com'], 'codePage': ['0'], 'userAccountControl': ['512'], 'lastLogon': ['130573332499193431'], 'uSNChanged': ['24499292'], 'givenName': ['testuser1'], 'lastLogoff': ['0']}), (None, ['ldap://ForestDnsZones.example.com/DC=ForestDnsZones,DC=example,DC=com']), (None, ['ldap://DomainDnsZones.example.com/DC=DomainDnsZones,DC=example,DC=com']), (None, ['ldap://example.com/CN=Configuration,DC=example,DC=com'])]

and this for uid=testuser1

[(None, ['ldap://ForestDnsZones.example.com/DC=ForestDnsZones,DC=example,DC=com']), (None, ['ldap://DomainDnsZones.example.com/DC=DomainDnsZones,DC=example,DC=com']), (None, ['ldap://example.com/CN=Configuration,DC=example,DC=com'])]

**Comment by apolkosnik** [comment] 2015-02-04 14:58
It looks like it should work out of the box at least for testuser1.
Perhaps the Jason account is locked.
Also,  remember that you need to have the accounts in crits created before
your ldap/AD users can get in.

**Comment by jcalafiore** [comment] 2015-02-05 15:35
Hi Adam,
 I've had some success. First of all, I didn't realize it was required to have the user set up in CRITS to allow an AD authenticate to work in CRITS.

I've encountered an issue, which I am still trying to figure out. When I log in to CRITS with the same Jason account I have to put the Domain prefix before(ie example\Jason) in order for it to log in. The testuser1 does not require this. Both user accounts are in the same OU, the only difference are the AD groups they are members of. I am experimenting with this at the moment. I found in your python script that if I added un='example\Jason' then it worked also, but it did not require this to work for testuser1.

I am curious what are the recommended setup in the CRITS LDAP settings.This is what I am currently using? Is there a way to define a specific OU for User accounts? I have tried adding OU=CRITS User Accounts, DC=example,DC=com in the LDAP settings and tried to log in with an account which is in a separate OU, and I was able to access it.
Ldap auth: Checked
Ldap tls: Not Checked
Ldap server: 10.0.0.1 
Ldap usercn: Blank
Ldap userdn: DC=example,DC=com
Ldap update on login: Checked


Thanks
Jason

**Comment by frbapolkosnik** [comment] 2015-02-05 15:50
Jason,
Your LDAP setup looks good.
Only thing that might be the cause of your issue is how the users are set up in LDAP.
OU based access in CRITs is not yet implemented, so you shouldn't worry much about that. If your LDAP server is on the same box as CRITs you might be able to get away with not using TLS, but actually using an encrypted channel is something that you should consider (since you don't want those passwords flying in plaintext).

On another note, I think that you can close this issue on github, and take this to the crits-users google discussion group for everyone's benefit.

Best regards,

Adam Polkosnik<mailto:adam.polkosnik@ny.frb.org>
National Incident Response Team
212.720.5839

**Comment by jcalafiore** [comment] 2015-02-05 16:10
Hi Adam,
 I turned on TLS and noticed now I can only log in as testuser1 and not Jason regardless of the Domain prefix is added. Same issue with another domain user account I tried. Is there anything on the domain controller that needs to be changed in order for this to work properly?

Thanks
Jason

**Comment by apolkosnik** [comment] 2015-02-05 16:40
You should really turn on the debug, and look into the logs.

The python code I gave you is pretty much the code that does the work in
CRITs, it's just easier to debug on the client side with the python script
than with CRITs.

Best regards,
Adam

**Comment by frbapolkosnik** [comment] 2015-02-05 18:02
One other thing that you need to keep in mind is that in case LDAP/AD is unavailable CRITs will use the local password for the account to log in. It’s actually a feature, that allows one to use CRITs in the event of the LDAP server failure.

**Comment by jcalafiore** [comment] 2015-02-05 20:05
Hi Adam, 
 I am looking into LDAPs, but will need to make some configuration changes in AD first. 

Otherwise I looked at the logs and noticed the following. It appears it is not able to do a bind with the 'jason' username. Couldn't figure why beyond that. I also tried to configure testuser1 with the same AD groups as jason and I am still getting the same issue. 

INFO 2015-02-05 13:36:47,940 crits.core.user Logging in user: example\jason
ERROR 2015-02-05 13:36:47,965 crits.core.user Error binding to LDAP for: jason
ERROR 2015-02-05 13:36:47,965 crits.core.user ERR: {'info': '80090308: LdapErr: DSID-0C0903A9, comment: AcceptSecurityContext error, data 52e, v1db1', 'desc': 'Invalid credentials'}
ERROR 2015-02-05 13:36:47,965 crits.core.user Error retrieving LDAP info for: jason
ERROR 2015-02-05 13:36:47,965 crits.core.user ERR: {'info': '000004DC: LdapErr: DSID-0C0906E8, comment: In order to perform this operation a successful bind must be completed on the connection., data 0, v1db1', 'desc': 'Operations error'}

INFO 2015-02-05 13:41:12,960 crits.core.user Logging in user: jason
INFO 2015-02-05 13:41:12,961 crits.core.user Invalid LDAP credentials for: jason

INFO 2015-02-05 13:37:48,199 crits.core.user Logging in user: example\testuser1
INFO 2015-02-05 13:37:48,214 crits.core.user Bound to LDAP for: testuser1
ERROR 2015-02-05 13:37:48,225 crits.core.user Error retrieving LDAP info for: testuser1
ERROR 2015-02-05 13:37:48,225 crits.core.user ERR: 'sn'

INFO 2015-02-05 13:40:35,053 crits.core.user Logging in user: testuser1
INFO 2015-02-05 13:40:35,066 crits.core.user Bound to LDAP for: testuser1
ERROR 2015-02-05 13:40:35,077 crits.core.user Error retrieving LDAP info for: testuser1
ERROR 2015-02-05 13:40:35,077 crits.core.user ERR: 'sn'


Thanks
Jason

**Comment by jcalafiore** [comment] 2015-02-26 18:56
Hi Adam,
 I wanted to follow-up regarding the issue.

I was able to figure out why I was not able to get LDAP working with certain users unless I added the domain prefix. Apparently the Display name field MUST have the username as that property. On some accounts that were not working that was changed to a Full Name.

Second, I am now working on setting up LDAPS as you suggested to enable TLS functionality. I've set up our AD certificate and it appears everything is working. I have used your python script you mentioned earlier for testing LDAPS. 

I have now enabled the TLS function in CRITS and I am able to login to the site, but I notice this error appearing in the crits.log file. Otherwise I have no way to tell if TLS is functioning properly.

INFO 2015-02-26 13:50:30,876 crits.core.user Logging in user: jason
INFO 2015-02-26 13:50:31,122 crits.core.user Bound to LDAP for: jason
ERROR 2015-02-26 13:50:31,123 crits.core.user Error retrieving LDAP info for: jason
ERROR 2015-02-26 13:50:31,123 crits.core.user ERR: list index out of range

**Comment by apolkosnik** [comment] 2015-02-26 19:06
That looks like you are hitting the second exception clause in
info_from_ldap() make sure that you have the attributes filled in as you
can see in crits/core/user.py:864-866

-A

**Comment by jcalafiore** [comment] 2015-02-26 19:21
Hi Adam,
 I am not exactly clear of what I should check/do.. are you saying I need to editing the user.py?

I looked for that field 'info_from_ldap() and found this on line  772

def info_from_ldap(self, config=None, password=''):
        """
        Get information about this user from LDAP.
        """

        import ldap, ldapurl
        resp = {"result": "ERROR"}
        if not config:
            config = CRITsConfig.objects().first()
        # Make sure we have the rquired settings, else return failure
        if not config.ldap_server or not config.ldap_userdn:
            return resp
        ldap_server = config.ldap_server.split(':')
        scheme = "ldap"
        if config.ldap_tls:
            scheme = "ldaps"
        url = ldapurl.LDAPUrl('%s://%s' % (scheme, ldap_server[0]))
        if len(ldap_server) == 2:
            l = ldap.initialize('%s:%s' % (url.unparse(),
                                           ldap_server[1]))
        else:
            l = ldap.initialize(url.unparse())
        l.protocol_version = 3
        l.set_option(ldap.OPT_REFERRALS, 0)
        l.set_option(ldap.OPT_TIMEOUT, 10)
        # setup auth for custom cn's
        cn = "cn="

**Comment by apolkosnik** [comment] 2015-02-26 19:25
no, you might be missing email, sn, and whatever it is for the first name
in your user's ldap data

**Comment by frbapolkosnik** [comment] 2015-02-26 19:54
Your LDAP accounts need to have these attributes defined

['givenName'],



['sn']


['mail']




Adam Polkosnik<mailto:adam.polkosnik@ny.frb.org>
National Incident Response Team
212.720.5839

**Comment by jcalafiore** [comment] 2015-02-26 19:59
Hi Adam,
 I checked those attributes First Name, Last Name, and email. They are all defined the same as the configuration in the CRITS Control Panel.

Jason

**Comment by apolkosnik** [comment] 2015-02-26 20:06
If you have option in CRITs checked to update data from LDAP, the first
name, last name, and email are taken from LDAP and updated in CRITs. But
for that to work properly you need sn, givenName, and mail set in LDAP for
your users.

**Comment by jcalafiore** [comment] 2015-02-26 20:48
Hi Adam,
 My linux test account does not give an error in crits.log but my jason account does. I've tried changing some of the settings for these users in AD, but no luck. 

Just curious what functionality is lost if we uncheck 'update data from LDAP' because I've noticed this does remove the error.

Jason

**Comment by jcalafiore** [comment] 2015-02-27 19:53
Hi Adam,
 As I mentioned earlier I have now enabled the TLS function in CRITs and I am able to login to the site. How do I tell if TLS is functioning properly within the application?

Jason

**Comment by frbapolkosnik** [comment] 2015-04-01 14:03
HI Jason,
Perhaps you can close this issue now.

**Closed** 2015-04-01 14:21 UTC
