### ISSUE TITLE
Triage not working for samples

### ISSUE THREAD

**Issue by DukeOfHazard** [crits/crits#545] opened 2015-07-29 01:19 UTC
Triage doesn't appear to be working for samples in master (and I suspect stable_4).  I tested multiple services with both files and metadata-only samples, with the same results.

**Comment by wxsBSD** [comment] 2015-07-29 20:26
What services are you running on triage? I think there may be a problem but you haven't provided enough to debug fully. In particular I think at least entropycalc will not run on triage, which may be a useful data point to note.

**Comment by webstergd** [comment] 2015-07-29 21:05
Are you able to manually execute the services with no errors? Do the
services start but stay in a running mode?

**Comment by wxsBSD** [comment] 2015-07-29 21:06
I did a bit of digging and have an idea what is going on. It relates to runtime forms and not being able to validate them properly. I have to run but should be able to get a fix published for this tomorrow.

**Comment by webstergd** [comment] 2015-07-29 21:09
If it helps, I have seen this hit my server with respect to Cuckoo.

**Comment by wxsBSD** [comment] 2015-07-29 21:12
This is a fix for the entropycalc service: https://github.com/crits/crits_services/compare/triage_fixes

I need to sweep other services before I submit a PR, but that should help you determine what other services are broken on triage.

**Comment by DukeOfHazard** [comment] 2015-07-29 22:10
I know the VirusTotal service is broken as well as.  It was the service where I first noticed the issue.

**Comment by wxsBSD** [comment] 2015-08-03 18:26
I just tested yara, peinfo, virustotal_lookup and entropycalc and all work fine on triage for a sample (entropycalc is with my fixes, which I will be pushing now). To help debug this I think we may need you to dive a bit deeper. Would you be willing to change https://github.com/crits/crits/blob/master/crits/services/handlers.py#L297 to log something (or otherwise tell you what exception was thrown)?

**Comment by DukeOfHazard** [comment] 2015-08-04 00:43
I can do that.  Should I just have it write information on the error to stdout?  I'm not very familiar with Django, so would that write the error out to the CRITS log or to one of the apache logs?

I appreciate the help.

**Comment by wxsBSD** [comment] 2015-08-04 01:23
If you are using runserver print statements go to stdout. If using Apache I think they go to error.log, but you should check the docs.

**Comment by wxsBSD** [comment] 2015-08-06 13:16
@webstergd Would you be willing to instrument the run_triage() code to see what is going on with the cuckoo service as I discussed above? It is either there or in the bind_runtime_form() for the service.

I am without a cuckoo install right now to be able to test this thoroughly.

**Comment by DukeOfHazard** [comment] 2015-08-06 15:20
I have some interesting results.  When I upload a sample (in this case, I was using MD5's), it doesn't appear that the code in "run_triage" gets called at all.  I confirmed this by setting the code to write to stderr whether or not an exception occurs.  The code does trigger and run when the Virustotal service is executed on triage for domains and IPs.  I also confirm that, even with your fixes, the entropycalc service wouldn't run on triage for me.

**Comment by wxsBSD** [comment] 2015-08-06 15:23
That is to expected. Triage is not run if we already have results for that sample (meaning it was a re-upload) or if we have no backing binary (meaning it was a metadata upload). https://github.com/crits/crits/blob/master/crits/samples/handlers.py#L985

**Comment by brlogan** [comment] 2015-08-06 20:34
Hey Wes, I think we agreed back in pull #1375 of legacy that data shouldn't be needed to run Triage, but never merged the change. Sometimes a metadata upload still benefits from Triage.

**Comment by DukeOfHazard** [comment] 2015-08-06 20:43
Just as an FYI, I've been doing testing with " and data" removed, and the services that are designed to work on binaries appear to fail gracefully if run on a metadata upload.

**Comment by wxsBSD** [comment] 2015-08-06 20:48
@brologan I vaguely remember that discussion. I'd be in favor of that change, especially since it seems to have been tested by @DukeOfHazard, if you wish to send a PR.

@DukeOfHazard Entropycalc service runs on triage just fine for me after these changes. Can you provide any more information (exceptions being thrown, traces, anything?) to help narrow this down?

There is also the outstanding cuckoo problem mentioned by @markedoe in another issue. I'm unable to debug that one and hope he can chime in here after some instrumentation.

**Comment by brlogan** [comment] 2015-08-06 22:16
@wxsBSD Unfortunately I've been asked to not submit PRs right now due to legal concerns, otherwise I'd be happy to. The change in 3.1 was as simple as removing the "and data" from
https://github.com/crits/crits/blob/master/crits/samples/handlers.py#L985

But I haven't tested in Stable 4.

**Comment by wxsBSD** [comment] 2015-08-06 22:27
Ok, I'll try and remember to get it in. Thanks @brlogan!

**Comment by webstergd** [comment] 2015-08-06 23:30
@wes: happy to check it out when I get back. Just finished presenting and flying back tomorrow!

**Comment by DukeOfHazard** [comment] 2015-08-11 13:57
@wxsBSD It looks like entropy_calc is working for my now after I did another pull from crits_services master.  Thank you for the assistance.

**Comment by webstergd** [comment] 2015-10-12 10:25
Just a quick update on Cuckoo. We had issues with using this service for triage. We can fix the issue but the main problem is that the the core of the problem is that the timeout for receiving results will expire before the service can complete. To fix this, we have rewritten the service under the microservices architecture and it us current under test. I will submit it after test is complete.

**Comment by larrymcd** [comment] 2015-12-02 20:01
@webstergd : any update on the cuckoo timeout issue?

**Comment by webstergd** [comment] 2015-12-02 22:15
The service needs to become distributed for cuckoo to really work for
triage. We pushed a few patches to make the core better able to support a
distributed service. Next step is to package the distributed service up in
a way that can be understood by all and clean up the template.

Patch for the template is in the works.
Patch for the service is complete and just being documented.

Sorry the guys working on this are all students. They are sometimes not the
fastest. :-p

**Comment by brlogan** [comment] 2016-06-04 02:59
I think Wes may have forgotten about allowing Triage for metadata only Samples, so I created a new PR #755.

**Closed** 2016-08-05 17:53 UTC
