### ISSUE TITLE
Error importing STIX ('@' in attribute name)

### ISSUE THREAD

**Issue by johnmccash** [crits/crits#374] opened 2015-01-22 15:37 UTC
I was just trying to import a dump of the FS-ISAC STIX export from Soltra, and ran across a problem. Some of the attribute names contain the '@' character, and this appears to be an issue. The specific error, shown at the bottom of the 'STIX Document' import window is "error parsing attribute name, line 342, column 72" The specified position in the STIX source file was an '@' character in an attribute name.

Is having an '@' in an attribute name a STIX violation, or is this a bug in Crits?

**Comment by johnmccash** [comment] 2015-01-22 15:51
Actually, this may not be as simple as I was thinking. The entry it's erroring on is actually an <indicator:Description> entry, which actually contains some data about an email message. the portion generating the error about the '@' is actually an email address of the form "Firstname Lastname <emailid@domain.com>

So rather than the '@', it's probably really complaining about the '<' and '>'

**Comment by johnmccash** [comment] 2015-01-22 16:27
If I fix that one, and proceed, I get another different issue further down the file:

xmlParseEntityref: no name, line 489, column 1118

This appears to be an issue with a '&' character, followed by a space,hh in an indicator:Description entry.

I would think there should be an option to allow crits to import all the lines that it can properly parse from a file, and maybe save the records containing improperly constructed STIX to another file

**Comment by johnmccash** [comment] 2015-01-22 17:22
According to the STIX descriptions at
http://stixproject.github.io/data-model/1.1.1/indicator/IndicatorType/
and
http://stixproject.github.io/data-model/1.1.1/stixCommon/StructuredTextType/
this apears to be an error in the Soltra STIX export. The page states with reference to Structuredtexttype, which is the type of 'indicator:Description', "Note that if the markup tags used by this format would be interpreted as XML information (such as the bracket-based tags of HTML) the text area should be enclosed in a CDATA section to prevent the markup from interferring with XML validation of the STIX document. If this attribute is absent, the implication is that no markup is being used."

I'll go over there, and tell them about this.

**Comment by mgoffin** [comment] 2015-01-22 18:34
Woah. Thanks for tracking all of this down! It could have been (and still could be) in one or both of the applications. I guess we can see what the Soltra devs have to say about it and go from there :)

**Comment by johnmccash** [comment] 2015-01-22 22:28
This also appears to affect (so far) filenames (FileObj:File_Name), email subjects (EmailMessageObj:Subject), and URIs (URIObj:Value).

**Comment by johnmccash** [comment] 2015-01-22 22:28
The issue also affects WinRegistryKeyObj:Data, possibly others as well. Stay tuned...

**Comment by johnmccash** [comment] 2015-01-23 21:04
It also affects MutexObj:Name.

**Comment by johnmccash** [comment] 2015-01-26 15:28
I've found a bunch more of these. At this point, I'm assumingthat none of the fields are being checked for XML sanity. I've been using the Microsoft XML Notepad, and the freeware xmlwf tools to troubleshoot these.

**Comment by gtback** [comment] 2015-01-26 16:01
You might be able to use the [STIX validator](http://stix-validator.readthedocs.org/en/latest/) to check documents before trying to import them into CRITs.

**Comment by johnmccash** [comment] 2015-01-26 16:02
I've finally (I think) gotten past all the pure XML syntax issues. However I'm now getting the "No version attribute set on xml instance. Unable to determine version compatibility" error. From my research, this should indicate an incompatible STIX version, but it's 1.1.1, as shown by this header:

 

<taxii_11:Content_Block xmlns:taxii="http://taxii.mitre.o..._xml_binding-1"xmlns:taxii_11="http://taxii.mitre.org/messages/taxii_xml_binding-1.1" xmlns:tdq="http://taxii.mitre.org/query/taxii_default_query-1"><taxii_11:Content_Binding binding_id="urn:stix.mitre.org:xml:1.1.1"/><taxii_11:Content><stix:STIX_Package xmlns:cyboxCommon="http://cybox.mitre.org/common-2" xmlns:cybox="http://cybox.mitre.org/cybox-2" xmlns:cyboxVocabs="http://cybox.mitre.org/default_vocabularies-2" xmlns:marking="http://data-marking.mitre.org/Marking-1" xmlns:tlpMarking="http://data-marking.mitre.org/extensions/MarkingStructure#TLP-1" xmlns:edge="http://soltra.com/" xmlns:indicator="http://stix.mitre.org/Indicator-2" xmlns:stixCommon="http://stix.mitre.org/common-1" xmlns:stixVocabs="http://stix.mitre.org/default_vocabularies-1" xmlns:stix="http://stix.mitre.org/stix-1" xmlns:CISCP="http://www.us-cert.gov/ciscp" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" id="edge:Package-342d0d3c-1619-4b4b-84ac-85bd95551769" version="1.1.1" timestamp="2015-01-22T15:02:50.888013+00:00">

 

Do I need to somehow extract all the individual STIX_Package elements, and import them separately?

 

Thanks

John

**Comment by gtback** [comment] 2015-01-26 16:18
I think you'll need to put "triple backticks" (```) above and below your XML example to get it to show up on GitHub. That error sounds familiar (and if I remember correctly, can be caused by things other than the STIX version), but I can't find where it's coming from. Do you have a traceback?

**Comment by gtback** [comment] 2015-01-26 16:25
It looks like the recent error is related to #302.

**Comment by johnmccash** [comment] 2015-01-26 16:31
Here are the first three lines of the file. note that this is actually the Soltra server, so it's technically in TAXII format, but that uses STIX to format the individual elements, I did try importing some of the individual STIX packages pulled manually out of the file, and I get "list index out of range".
Thoughts?
John


```
<taxii_11:Poll_Response collection_name="system.Default" in_response_to="1275630184" xmlns:taxii_11="http://taxii.mitre.org/messages/taxii_xml_binding-1.1" message_id="19056" more="false"><taxii_11:Inclusive_End_Timestamp>2015-01-22T15:02:50.861568+00:00</taxii_11:Inclusive_End_Timestamp>
<taxii_11:Content_Block xmlns:taxii="http://taxii.mitre.org/messages/taxii_xml_binding-1" xmlns:taxii_11="http://taxii.mitre.org/messages/taxii_xml_binding-1.1" xmlns:tdq="http://taxii.mitre.org/query/taxii_default_query-1"><taxii_11:Content_Binding binding_id="urn:stix.mitre.org:xml:1.1.1"/><taxii_11:Content><stix:STIX_Package xmlns:cyboxCommon="http://cybox.mitre.org/common-2" xmlns:cybox="http://cybox.mitre.org/cybox-2" xmlns:cyboxVocabs="http://cybox.mitre.org/default_vocabularies-2" xmlns:marking="http://data-marking.mitre.org/Marking-1" xmlns:tlpMarking="http://data-marking.mitre.org/extensions/MarkingStructure#TLP-1" xmlns:edge="http://soltra.com/" xmlns:indicator="http://stix.mitre.org/Indicator-2" xmlns:stixCommon="http://stix.mitre.org/common-1" xmlns:stixVocabs="http://stix.mitre.org/default_vocabularies-1" xmlns:stix="http://stix.mitre.org/stix-1" xmlns:CISCP="http://www.us-cert.gov/ciscp" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" id="edge:Package-342d0d3c-1619-4b4b-84ac-85bd95551769" version="1.1.1" timestamp="2015-01-22T15:02:50.888013+00:00">
    <stix:STIX_Header>

```

**Comment by johnmccash** [comment] 2015-01-26 17:48
Stupid question: Should this work? Either importing the full file with the top level of taxii_11:Poll_Response, or opening a file saved from that, and just containing one of the stix:STIX_Package elements? I'm currently assuming the answer is yes, but I may be misusing something.

If  opening a file containing only one of the stix:STIX_Package elements should work, where might I look for an error log explaining the cause of the "list index out of range" message?
Thanks

**Comment by johnmccash** [comment] 2015-01-26 18:06
Stupid Followup Question: Does anyone have an example of a short STIX file that does import correctly, so I can compare against what I have that's failing?

**Comment by johnmccash** [comment] 2015-01-26 18:15
Nevermind the sample request. I found some.

**Comment by johnmccash** [comment] 2015-01-26 19:58
This "list index out of range" problem appears to be an issue with Crits. The XML doc I extracted from the FSICAC export and am attempting to import seems to be correct. It passes the stix_validator schema checks. Any suggestions on how to troubleshoot this?

**Comment by gtback** [comment] 2015-01-27 20:23
@johnmccash: If you can paste a traceback (copied from Django or from web server logs), that would be helpful. Also, can you send the document (sanitized if necessary, but retaining the structure) to stix@mitre.org? One of us can hopefully figure out where the problem is.

**Comment by johnmccash** [comment] 2015-01-27 21:19
The problem is that I can't find the error in any logs. It only shows up in the browser window from which I'm attempting to run the import. Assuming it's not being written to a log that's just buried somewhere, how do I enable additional logging to try and localize the issue?

**Comment by johnmccash** [comment] 2015-01-27 21:46
I've sent a redacted file to stix@mitre.org.

**Comment by gtback** [comment] 2015-01-28 14:19
Oh, I didn't realize this was submitted via an AJAX call, so the errors are swallowed and not logged anywhere. After a bit of debugging, I found that the `IndexError: list index out of range` was caused by [this line](https://github.com/crits/crits/blob/f2d4f4caa8197e059308ef4f63a5d95fd5471042/crits/events/event.py#L127) and the fact that there is no `Package_Intent` in the STIX you are providing. You can try to work around this by not checking the `Create event` checkbox, but I was then running into other errors:

```
ID: fsisac:uri-88888888-8888-8888-8888-888888888888

"Observable" is currently unsupported for input into CRITs.
```  

I'm not a CRITs developer, so I'm not sure the best way to go about fixing it. As far as I can tell, there's nothing wrong with the STIX document, except that perhaps not everything in it is supported by CRITs.

**Comment by johnmccash** [comment] 2015-01-28 15:53
Greg,
                OK… I tried the workaround you suggested, and got the ‘observable unsupported’ response with that particular sample. Then I tried it with another one that wasn’t using stix:Observables, but was using stix:Indicator and indicator:Observable instead. This attempt netted me a different error, “local variable 'item' referenced before assignment”. I’m attaching a redacted copy of the file that garnered this error.

                Am I correct in interpreting that there are (at least) two different ways to express any given indicator in STIX? One being via stix:Indicator, and the other via stix:Observable? If so, then it appears that Soltra or FS-ISAC are going the Observable route, and Crits the Indicator path… If that’s correct, we basically have two completely incompatible (at least as far as real information sharing goes) standards. Is that right?

                One last thing… Should the STIX import functionality support reading a TAXII dump file containing  multiple stix:STIX_Package elements? If not, what’s the proper way to process and import such a file? I’d imagine there must be utilities capable of breaking out all the individual stix:STIX_Package elements, and importing them separately, but I haven’t been able to find anything.

                                Thanks
                                                John

**Comment by mgoffin** [comment] 2015-09-02 20:53
This is no longer an issue in core and if it is still an issue, should be fixed in the TAXII service.

**Closed by mgoffin** 2015-09-02 20:53 UTC
